Repository TeamTouchDown/perflow-frontend, pull requests merged in 2024-12, with the labels that each got.

#2 [setting] #1 frontend 프로젝트 초기 세팅
  .gitignore
  perflow-frontend/.vscode/extensions.json
  perflow-frontend/.vscode/settings.json
  perflow-frontend/index.html
  perflow-frontend/jsconfig.json
  perflow-frontend/package-lock.json
  perflow-frontend/package.json
  perflow-frontend/public/favicon.ico
  perflow-frontend/src/App.vue
  perflow-frontend/src/assets/test.txt
  perflow-frontend/src/components/test.txt
  perflow-frontend/src/config/test.txt
  perflow-frontend/src/main.js
  perflow-frontend/src/router/router.js
  perflow-frontend/src/store/store.js
  perflow-frontend/src/views/test.txt
  perflow-frontend/vite.config.js
Labels: ⚙ Setting

#4 [feat/common]: #3 공용 버튼 구현 완료, 공용 표 구현 중
  perflow-frontend/index.html
  perflow-frontend/src/App.vue
  perflow-frontend/src/assets/global.css
  perflow-frontend/src/components/common/ButtonBasic.vue
  perflow-frontend/src/components/common/TableBasic.vue
  perflow-frontend/src/main.js
Labels: ✨ Feat

#6 [feat/hr] #5 pinia초기 설정. axios 초기설정. interceptor 작성, 로그인 로그아웃 기능 작성
  perflow-frontend/package-lock.json
  perflow-frontend/package.json
  perflow-frontend/src/App.vue
  perflow-frontend/src/config/axios.js
  perflow-frontend/src/config/test.txt
  perflow-frontend/src/main.js
  perflow-frontend/src/store/authStore.js
  perflow-frontend/src/store/store.js
  perflow-frontend/src/views/EmpLogin.vue
  perflow-frontend/src/views/test.txt
Labels: ✨ Feat

#9 [feat/hr] #8 조직도 트리 구조 구현
  perflow-frontend/src/App.vue
  perflow-frontend/src/components/common/OrganizationNode.vue
  perflow-frontend/src/components/common/OrganizationSelectedEmp.vue
  perflow-frontend/src/components/common/OrganizationTree.vue
  perflow-frontend/src/main.js
  perflow-frontend/src/store/store.js
Labels: ✨ Feat

#17 [feat/approval/#15]: 입력 필드 공용 컴포넌트 추가
  perflow-frontend/src/components/common/ApprovalShareBox.vue
  perflow-frontend/src/components/common/ButtonBasic.vue
  perflow-frontend/src/components/common/InputField.vue
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/ApprovalHome.vue
  perflow-frontend/src/views/TemplateBasic.vue
  perflow-frontend/src/views/newDoc.vue
Labels: ✨ Feat, 🎨 Style

#20 [feat/#11]: 공용컴포넌트
  perflow-frontend/package-lock.json
  perflow-frontend/package.json
  perflow-frontend/src/assets/image/arrow_down_1.png
  perflow-frontend/src/assets/image/arrow_down_2.png
  perflow-frontend/src/assets/image/arrow_up_1.png
  perflow-frontend/src/assets/image/arrow_up_2.png
  perflow-frontend/src/assets/image/calendar.png
  perflow-frontend/src/assets/image/download_2.png
  perflow-frontend/src/assets/image/next.png
  perflow-frontend/src/assets/image/previous.png
  perflow-frontend/src/assets/image/search.png
  perflow-frontend/src/assets/image/upload.png
  perflow-frontend/src/assets/image/upload_2.png
  perflow-frontend/src/components/common/ButtonDropDown.vue
  perflow-frontend/src/components/common/DateSearchBar.vue
  perflow-frontend/src/components/common/ExcelDropDown.vue
  perflow-frontend/src/components/common/FileUpload.vue
  perflow-frontend/src/components/common/PagingBar.vue
  perflow-frontend/src/components/common/SearchBar.vue
Labels: ✨ Feat

#27 이슈템플릿 재생성
  .github/ISSUE_TEMPLATE/이슈템플릿.md
Labels: ⚙ Setting

#29 [fix] : #26 패키지 수정
  perflow-frontend/package-lock.json
  perflow-frontend/package.json
Labels: 🐞 Bug

#31 [fix] : #30 타이머에 로그인 확인 로직 추가
  perflow-frontend/src/store/authStore.js
Labels: 🐞 Bug

#36 [feat/hr] #32 사원 일괄 등록 기능 구현, 뒤로가기 버튼 구현, 파일 업로드 컴포넌트 수정
  perflow-frontend/src/App.vue
  perflow-frontend/src/assets/image/check.png
  perflow-frontend/src/assets/image/delete.png
  perflow-frontend/src/components/common/ButtonBack.vue
  perflow-frontend/src/components/common/ButtonLong.vue
  perflow-frontend/src/components/common/FileUpload.vue
  perflow-frontend/src/components/common/Loading.vue
  perflow-frontend/src/components/common/TableBasic.vue
  perflow-frontend/src/components/common/TableCheck.vue
  perflow-frontend/src/router/router.js
  perflow-frontend/src/store/authStore.js
  perflow-frontend/src/store/store.js
  perflow-frontend/src/views/approval/WaitingDoc.vue
  perflow-frontend/src/views/hr/employee/EmpList.vue
  perflow-frontend/src/views/hr/employee/EmpListRegister.vue
Labels: ✨ Feat, 🎨 Style

#37 [feat/attitude]/#21: 인사팀 조회 페이지 구현
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/Attitude/Annual.vue
  perflow-frontend/src/views/Attitude/AttendanceStatus.vue
  perflow-frontend/src/views/Attitude/Overtime.vue
  perflow-frontend/src/views/Attitude/Travel.vue
  perflow-frontend/src/views/Attitude/Vacation.vue
  perflow-frontend/src/views/Attitude/WorkHours.vue
  perflow-frontend/src/views/Attitude/WorkStatus.vue
Labels: ✨ Feat

#35 [feat/payment/#22]: 급여대장 리스트
  perflow-frontend/package-lock.json
  perflow-frontend/package.json
  perflow-frontend/src/assets/image/down.png
  perflow-frontend/src/assets/image/flat.png
  perflow-frontend/src/assets/image/up.png
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/hr/employee/EmpList.vue
  perflow-frontend/src/views/payment/PayrollList.vue
  perflow-frontend/src/views/payment/ThreeMonthChart.vue
  perflow-frontend/src/views/payment/ThreeYearByMonthChart.vue
  perflow-frontend/src/views/payment/ThreeYearChart.vue
Labels: ✨ Feat, 🎨 Style

#41 [feat/payment/#40]: tooltip 컴포넌트
  perflow-frontend/src/components/common/ToolTip.vue
  perflow-frontend/src/views/payment/PayrollList.vue
Labels: ✨ Feat

#46 [Feat/attitude]/#38: 월별 주차별 근무 현황 조회(인사팀 ver)
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/Attitude/WorkStatus.vue
  perflow-frontend/src/views/Attitude/WorkStatusForEmpWeek.vue
  perflow-frontend/src/views/Attitude/WorkStatusForHRWeek.vue
  perflow-frontend/src/views/Attitude/WorkStatusForTeamLeaderWeek.vue
Labels: ✨ Feat

#48 [feat/perfo] : #28 개인,팀 KPI 등록 화면 구현
  perflow-frontend/src/components/common/PersonalKpiTable.vue
  perflow-frontend/src/components/common/TeamKpiTable.vue
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/performance/PersonalKPIView.vue
  perflow-frontend/src/views/performance/TeamKPIView.vue
Labels: ✨ Feat

#51 [feat/attitude]/#47 주차별 월별 근무 현황 조회
  perflow-frontend/src/views/Attitude/WorkStatusForEmpWeek.vue
  perflow-frontend/src/views/Attitude/WorkStatusForHRWeek.vue
  perflow-frontend/src/views/Attitude/WorkStatusForTeamLeaderWeek.vue
Labels: ✨ Feat

#52 [feat/hr] #45 메인페이지 기능 구현
  perflow-frontend/src/assets/image/arrow-right.png
  perflow-frontend/src/components/common/NavigationBar.vue
  perflow-frontend/src/components/modifyer/AddressInputFeild.vue
  perflow-frontend/src/components/modifyer/ModifyInputFeild.vue
  perflow-frontend/src/components/modifyer/SubmitButton.vue
  perflow-frontend/src/components/modifyer/modifySideBar.vue
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/hr/employee/EmpLogin.vue
  perflow-frontend/src/views/hr/employee/EmpMyPage.vue
Labels: ✨ Feat

#56 [Feat/hr] #53 사원 개별 등록 기능 구현
  perflow-frontend/src/components/common/ButtonDropDown.vue
  perflow-frontend/src/components/hr/AddressInputField.vue
  perflow-frontend/src/components/hr/HeaderContainer.vue
  perflow-frontend/src/components/hr/ModifyInputFeild.vue
  perflow-frontend/src/components/hr/RegisterInputField.vue
  perflow-frontend/src/components/hr/RrnInputField.vue
  perflow-frontend/src/components/hr/SubmitButton.vue
  perflow-frontend/src/components/hr/modifySideBar.vue
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/hr/employee/EmpListRegister.vue
  perflow-frontend/src/views/hr/employee/EmpMyPage.vue
  perflow-frontend/src/views/hr/employee/EmpRegister.vue
Labels: ✨ Feat, 🎨 Style

#57 [feat/#42]: 메인페이지
  perflow-frontend/src/assets/image/alarm.png
  perflow-frontend/src/assets/image/beach.png
  perflow-frontend/src/assets/image/left.png
  perflow-frontend/src/assets/image/luggage.png
  perflow-frontend/src/assets/image/payments.png
  perflow-frontend/src/assets/image/travel.png
  perflow-frontend/src/assets/image/work_off.png
  perflow-frontend/src/assets/image/work_on.png
  perflow-frontend/src/components/common/MainPageButton.vue
  perflow-frontend/src/components/common/TableMini.vue
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/MainPage.vue
Labels: ✨ Feat, 🎨 Style

#59 [feat/approval/#34]: 대기 문서 조회/결재 문서 생성
  perflow-frontend/src/assets/icons/arrow_forward_slim.png
  perflow-frontend/src/components/common/ApprovalShareBox.vue
  perflow-frontend/src/components/common/ModalBasic.vue
  perflow-frontend/src/components/common/OrganizationSelectedEmp.vue
  perflow-frontend/src/components/common/OrganizationTree.vue
  perflow-frontend/src/config/approval.js
  perflow-frontend/src/views/approval/ApprovalHome.vue
  perflow-frontend/src/views/approval/TemplateBasic.vue
  perflow-frontend/src/views/approval/WaitingDoc.vue
Labels: ✨ Feat, 🎨 Style

#60 [chore] : #58 메인페이지 라우팅 추가, 자잘한 수정
  perflow-frontend/src/App.vue
  perflow-frontend/src/components/common/NavigationBar.vue
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/Test.vue
  perflow-frontend/src/views/hr/employee/EmpLogin.vue
Labels: ✨ Feat

#63 [chore/#62]: 근무시간 동적으로 수정
  perflow-frontend/src/views/MainPage.vue
Labels: ✨ Feat

#70 [feat/payment/#54]: 급여상세조회
  perflow-frontend/src/assets/image/active.png
  perflow-frontend/src/components/common/TableMove.vue
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/payment/PayrollDetail.vue
  perflow-frontend/src/views/payment/PayrollList.vue
Labels: ✨ Feat

#72 [feat/payment/#69]: 급여 명세서 조회
  perflow-frontend/src/assets/image/allowance.png
  perflow-frontend/src/components/common/MainPageButton.vue
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/payment/PayStub.vue
Labels: ✨ Feat, 🎨 Style

#75 [feat/perfo] #49 KPI 조회 페이지 구현
  perflow-frontend/src/components/common/ButtonDropDown.vue
  perflow-frontend/src/components/common/KpiRecordSection.vue
  perflow-frontend/src/components/common/KpiSection.vue
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/performance/KPIRecordView.vue
  perflow-frontend/src/views/performance/KPIUpdateView.vue
Labels: ✨ Feat

#77 [Feat/hr] #67 회사관리/권한관리/부서관리 페이지 구현
  perflow-frontend/src/components/common/SearchButtonDropDown.vue
  perflow-frontend/src/components/common/SideMenuNode.vue
  perflow-frontend/src/components/common/SlideToggle.vue
  perflow-frontend/src/components/hr/ModifyInputFeild.vue
  perflow-frontend/src/components/hr/department/DepartmentNode.vue
  perflow-frontend/src/components/hr/department/DepartmentSelectedEmp.vue
  perflow-frontend/src/components/hr/department/DepartmentTree.vue
  perflow-frontend/src/components/hr/sideBar/AppointRegisterSideBar.vue
  perflow-frontend/src/components/hr/sideBar/CompanyInfoModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/CompanyPolicyModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/DepartmentRegisterSideBar.vue
  perflow-frontend/src/components/hr/sideBar/EmployeeModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/JobRegisterSideBar.vue
  perflow-frontend/src/components/hr/sideBar/PositionRegisterSideBar.vue
  perflow-frontend/src/config/axios.js
  perflow-frontend/src/router/router.js
  perflow-frontend/src/store/authStore.js
  perflow-frontend/src/store/store.js
  perflow-frontend/src/views/MainPage.vue
  perflow-frontend/src/views/hr/AppointList.vue
  perflow-frontend/src/views/hr/Authority.vue
  perflow-frontend/src/views/hr/DepartmentList.vue
  perflow-frontend/src/views/hr/JobList.vue
  perflow-frontend/src/views/hr/PositionList.vue
  perflow-frontend/src/views/hr/company/Company.vue
  perflow-frontend/src/views/hr/company/CompanyInfo.vue
  perflow-frontend/src/views/hr/company/CompanyPolicy.vue
  perflow-frontend/src/views/hr/employee/EmpList.vue
  perflow-frontend/src/views/hr/employee/EmpMyPage.vue
  perflow-frontend/src/views/hr/employee/EmpPwdRegister.vue
Labels: ✨ Feat, 🎨 Style

#80 [refactor/#78]: 메인 페이지 수정
  perflow-frontend/src/views/MainPage.vue
Labels: 🔨 Refactor

#81 [refactor/payment/#74]: 급여 명세서 조회 수정
  perflow-frontend/src/views/payment/PayStub.vue
Labels: 🔨 Refactor

#89 [feat/ann/]: #68 공지사항 생성 뷰 구현
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/announcement/AnnCreate.vue
  perflow-frontend/src/views/announcement/AnnList.vue
Labels: ✨ Feat, 🎨 Style

#90 [deploy] : main.yml 생성
  .github/workflows/main.yml
Labels: 🌏 Deploy

#92 [deploy] 프론트 배포 워크플로우 수정
  .github/workflows/main.yml
Labels: 🌏 Deploy

#95 deploy: main.yml 수정
  .github/workflows/main.yml
Labels: 🌏 Deploy

#96 [feat/payment/#84]: 퇴직금 명세서
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/payment/SeverancePayStub.vue
Labels: ✨ Feat

#99 [feat/payment/#97]: 예상 퇴직금 계산기
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/payment/Calculator.vue
  perflow-frontend/src/views/payment/SeverancePayStub.vue
Labels: ✨ Feat

#101 [refactor/perfo/#76]: KPI 관련 페이지 수정
  perflow-frontend/src/components/common/ButtonDropDown.vue
  perflow-frontend/src/components/common/KpiTable.vue
  perflow-frontend/src/components/common/TeamKpiTable.vue
  perflow-frontend/src/views/performance/KPIRecordView.vue
  perflow-frontend/src/views/performance/KPIUpdateView.vue
  perflow-frontend/src/views/performance/PersonalKPIView.vue
  perflow-frontend/src/views/performance/TeamKPIView.vue
Labels: 🔨 Refactor

#102 [chore/#100]: 메인 페이지 출근 기록 수정
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/Attitude/Attendance/QRModal.vue
  perflow-frontend/src/views/MainPage.vue
Labels: ✨ Feat

#105 [chore/#104]: 메인 페이지 예정 휴가 수정
  perflow-frontend/src/views/MainPage.vue
  perflow-frontend/src/views/payment/PayrollList.vue
  perflow-frontend/src/views/payment/SeverancePay.vue
Labels: 🔨 Refactor

#107 [chore/#106]: 연차 일 수 수정
  perflow-frontend/src/views/MainPage.vue
Labels: 🔨 Refactor

#113 [feat/vacation/#86] 휴가 신청 수정 모달 만들기
  perflow-frontend/src/views/Attitude/Annual/Annual.vue
  perflow-frontend/src/views/Attitude/Annual/AnnualModal.vue
  perflow-frontend/src/views/Attitude/Annual/AnnualUpdateModal.vue
  perflow-frontend/src/views/Attitude/Attendance/QRModal.vue
  perflow-frontend/src/views/Attitude/Vacation/VacationForEmp.vue
  perflow-frontend/src/views/MainPage.vue
Labels: ✨ Feat

#116 [feat/vacation/#86] 인사팀, 팀장 메뉴 설정
  perflow-frontend/src/router/router.js
  perflow-frontend/src/views/Attitude/Annual/AnnualForHR.vue
  perflow-frontend/src/views/Attitude/Annual/AnnualForLeader.vue
  perflow-frontend/src/views/Attitude/Attendance/Attendance.vue
  perflow-frontend/src/views/Attitude/Overtime/OvertimeForHR.vue
  perflow-frontend/src/views/Attitude/Overtime/OvertimeForLeader.vue
  perflow-frontend/src/views/Attitude/Travel/TravelForHR.vue
  perflow-frontend/src/views/Attitude/Travel/TravelForLeader.vue
  perflow-frontend/src/views/Attitude/Vacation/VacationForHR.vue
  perflow-frontend/src/views/Attitude/Vacation/VacationForLeader.vue
Labels: ✨ Feat

#122 [feat/#120]: 알림 창 컴포넌트 생성
  perflow-frontend/src/components/common/Alert.vue
Labels: ✨ Feat

#123 [doc]: readme 작성
  README.md
Labels: 📃 Docs
