Repository TeamTouchDown/perflow-frontend, pull requests merged in 2025-01, with the labels that each got.

#130 [feat/payment/#103]: 보험료 설정
  perflow-frontend/src/components/common/ExcelDropDown.vue
  perflow-frontend/src/views/payment/PayrollList.vue
Labels: ✨ Feat

#135 [feat/#134]: alert 창 연결
  perflow-frontend/src/views/payment/PayrollDetail.vue
  perflow-frontend/src/views/payment/PayrollList.vue
  perflow-frontend/src/views/payment/SeverancePay.vue
  perflow-frontend/src/views/payment/SeverancePayDetail.vue
Labels: ✨ Feat

#137 [fix]: modal 수정
  perflow-frontend/src/components/common/NavigationBar.vue
  perflow-frontend/src/components/hr/sideBar/AppointRegisterSideBar.vue
  perflow-frontend/src/components/hr/sideBar/CompanyInfoModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/CompanyPolicyModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/DepartmentRegisterSideBar.vue
  perflow-frontend/src/components/hr/sideBar/EmployeeDetailModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/EmployeeModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/JobModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/JobRegisterSideBar.vue
  perflow-frontend/src/components/hr/sideBar/PositionModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/PositionRegisterSideBar.vue
  perflow-frontend/src/views/hr/Authority.vue
  perflow-frontend/src/views/hr/employee/EmpListRegister.vue
  perflow-frontend/src/views/hr/employee/EmpLogin.vue
  perflow-frontend/src/views/hr/employee/EmpPwdRegister.vue
  perflow-frontend/src/views/hr/employee/EmpRegister.vue
Labels: 🐞 Bug

#138 [Fix] #136 emit에 맞게 수정
  perflow-frontend/src/components/hr/sideBar/AppointRegisterSideBar.vue
  perflow-frontend/src/components/hr/sideBar/CompanyInfoModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/CompanyPolicyModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/DepartmentRegisterSideBar.vue
  perflow-frontend/src/components/hr/sideBar/EmployeeDetailModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/EmployeeModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/JobModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/JobRegisterSideBar.vue
  perflow-frontend/src/components/hr/sideBar/PositionModifySideBar.vue
  perflow-frontend/src/components/hr/sideBar/PositionRegisterSideBar.vue
  perflow-frontend/src/views/hr/Authority.vue
  perflow-frontend/src/views/hr/employee/EmpLogin.vue
  perflow-frontend/src/views/hr/employee/EmpPwdRegister.vue
  perflow-frontend/src/views/hr/employee/EmpRegister.vue
Labels: 🐞 Bug

#139 [fix]: 네비게이션바 수정
  perflow-frontend/src/components/common/NavigationBar.vue
Labels: 🐞 Bug

#142 [feat/payment/#141] : 뒤로가기
  perflow-frontend/src/views/payment/PayrollDetail.vue
  perflow-frontend/src/views/payment/SeverancePayDetail.vue
Labels: ✨ Feat

#146 [feat/noti]: 로그아웃 시 FCM 토큰 제거 및 알림 목록 구현
  perflow-frontend/package-lock.json
  perflow-frontend/package.json
  perflow-frontend/public/firebase-messaging-sw.js
  perflow-frontend/src/assets/image/notification.png
  perflow-frontend/src/components/common/NavigationBar.vue
  perflow-frontend/src/config/notification/FcmService.js
  perflow-frontend/src/config/notification/firebase-messaging-sw.js
  perflow-frontend/src/config/notification/firebase.js
  perflow-frontend/src/main.js
  perflow-frontend/src/store/authStore.js
  perflow-frontend/src/views/hr/employee/EmpLogin.vue
  perflow-frontend/src/views/notification/FcmService.js
  perflow-frontend/vite.config.js
Labels: ✨ Feat, 🎨 Style

#151 [chore/noti]: #148 서비스워커 파일 위치 수정
  perflow-frontend/src/config/firebase-messaging-sw.js
  perflow-frontend/vite.config.js
Labels: 🐞 Bug

#152 [chore/noti]: 서비스워커 파일명 지정
  perflow-frontend/vite.config.js
Labels: 🐞 Bug

#154 [Fix] #153 네비게이션바 정상화
  perflow-frontend/src/components/common/NavigationBar.vue
Labels: 🐞 Bug

#163 [refactor/noti]: afterLogin 비동기 처리로 로그인 시간 감소
  perflow-frontend/src/views/hr/employee/EmpLogin.vue
Labels: 🔨 Refactor

#165 [feat/noti]: 백그라운드, 포그라운드 알림 클릭 이벤트 설정
  perflow-frontend/src/config/notification/FcmService.js
  perflow-frontend/src/firebase-messaging-sw.js
Labels: ✨ Feat

#169 [chore/payment/#145]: 여러가지 수정
  perflow-frontend/src/views/payment/OneYearChart.vue
  perflow-frontend/src/views/payment/PayStub.vue
  perflow-frontend/src/views/payment/PayrollDetail.vue
  perflow-frontend/src/views/payment/PayrollList.vue
  perflow-frontend/src/views/payment/SeverancePayDetail.vue
  perflow-frontend/src/views/payment/SeverancePayStub.vue
Labels: 🔨 Refactor

#173 [style/approval/#171] TableCheck height 수정
  perflow-frontend/src/components/common/TableCheck.vue
  perflow-frontend/src/views/approval/TemplateBasic.vue
Labels: 🎨 Style

#174 [style/noti]: 알림 목록 조회 시 삭제, 전체 삭제 추가
  perflow-frontend/src/components/common/NavigationBar.vue
Labels: ✨ Feat, 🎨 Style

#178 [chore/payment/#170]: 여러가지 수정
  perflow-frontend/src/components/common/Alert.vue
  perflow-frontend/src/components/common/TableMove.vue
  perflow-frontend/src/views/MainPage.vue
  perflow-frontend/src/views/payment/OneYearChart.vue
  perflow-frontend/src/views/payment/PayStub.vue
  perflow-frontend/src/views/payment/PayrollDetail.vue
  perflow-frontend/src/views/payment/PayrollList.vue
  perflow-frontend/src/views/payment/SeverancePay.vue
  perflow-frontend/src/views/payment/SeverancePayDetail.vue
  perflow-frontend/src/views/payment/SeverancePayStub.vue
Labels: 🔨 Refactor

#182 [chore/attitude/#181] 잔잔바리 에러 수정 상태 바 고치기
  perflow-frontend/src/views/Attitude/Overtime/Overtime.vue
  perflow-frontend/src/views/Attitude/Overtime/OvertimeForLeader.vue
  perflow-frontend/src/views/Attitude/Travel/Travel.vue
  perflow-frontend/src/views/Attitude/Vacation/VacationForEmp.vue
Labels: 🔨 Refactor

#188 chore/attitude/emergency 수정 showAlert만들기
  perflow-frontend/src/views/Attitude/Annual/AnnualUpdateModal.vue
  perflow-frontend/src/views/Attitude/Overtime/OvertimeUpdateModal.vue
  perflow-frontend/src/views/Attitude/Travel/TravelUpdateModal.vue
  perflow-frontend/src/views/Attitude/Vacation/VacationUpdateModal.vue
Labels: 🔨 Refactor

#196 [fix]: #191 자잘한 수정
  perflow-frontend/src/components/common/NavigationBar.vue
  perflow-frontend/src/views/MainPage.vue
  perflow-frontend/src/views/hr/DepartmentList.vue
  perflow-frontend/src/views/payment/Calculator.vue
  perflow-frontend/src/views/payment/PayrollList.vue
  perflow-frontend/src/views/payment/SeverancePay.vue
Labels: 🐞 Bug

#197 fix/attitude 수정
  perflow-frontend/src/views/Attitude/Annual/AnnualForLeader.vue
  perflow-frontend/src/views/Attitude/Annual/AnnualModal.vue
  perflow-frontend/src/views/Attitude/Annual/AnnualUpdateModal.vue
  perflow-frontend/src/views/Attitude/Overtime/OvertimeForLeader.vue
  perflow-frontend/src/views/Attitude/Overtime/OvertimeModal.vue
  perflow-frontend/src/views/Attitude/Overtime/OvertimeUpdateModal.vue
  perflow-frontend/src/views/Attitude/Travel/TravelForLeader.vue
  perflow-frontend/src/views/Attitude/Travel/TravelModal.vue
  perflow-frontend/src/views/Attitude/Travel/TravelUpdateModal.vue
  perflow-frontend/src/views/Attitude/Vacation/VacationForLeader.vue
  perflow-frontend/src/views/Attitude/Vacation/VacationModal.vue
  perflow-frontend/src/views/Attitude/Vacation/VacationUpdateModal.vue
Labels: 🔨 Refactor

#202 [feat/ann]: alert 창 변경
  perflow-frontend/src/views/announcement/AnnCreate.vue
  perflow-frontend/src/views/announcement/AnnDetail.vue
  perflow-frontend/src/views/announcement/AnnUpdate.vue
Labels: ✨ Feat
